### ISSUE TITLE
Keep pinned dependencies in `2.nnn.x/pom.xml` up to date

### ISSUE THREAD

**Issue by jglick** [jenkinsci/bom#1019]
Currently only `bom-weekly` is managed by Dependabot. For example, #1006 updated the version of `credentials` in `bom-weekly` to one which includes a recent security fix (among other changes); but `bom-2.303.x` and `bom-2.332.x` both continue to specify an older version, despite the availability of versions `2.6.1.1` and `1087.1089.v2f1b_9a_b_040e4`, respectively. (Not sure offhand what line `1074.1076.v39c30cecb_0e2` exists for.)

We deliberately decline to mention these POMs in `.github/dependabot.yml` because then we would constantly be rejecting suggestions to update pinned versions to plugin releases which in fact require a new core (see #266), so to do this automatically we would need to use `updatecli` or something else customizable (e.g., checking the public update center for updates for a given LTS line).

**Comment by jetersen** [comment]
updatecli plugin would be feasible, I am not sure how along they are with out of tree plugins, but potentially it could also be in tree plugin to updatecli for `jenkins-plugins` plugin 😓

Potentially we could also use updatecli's option for a shellscript :)

**Comment by jetersen** [comment]
@lemeurherve @jglick I got something working in #1063 by using updatecli, [plugin-manager](https://github.com/jenkinsci/plugin-installation-manager-tool) and powershell for xml and output
