### ISSUE TITLE
Weekly updates stopped working

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#1130]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04.4 LTS x86_64
Jenkins 2.344

### Reproduction steps

Release a weekly, then wait a few days for Updatecli to propose an update.

### Expected Results

A PR is proposed for the update, such as https://github.com/jenkinsci/bom/pull/1023.

### Actual Results

https://github.com/jenkinsci/bom/pull/1023 was the last such PR that was proposed (for 2.344). For the past month, no additional PRs have been proposed for 2.345, 2.346, or 2.347.

### Anything else?

This is correlated with (but not necessarily caused by) the introduction of #1063 CC @jetersen

**Comment by timja** [comment]
The branch is here:
https://github.com/jenkinsci/bom/compare/updatecli_1d4a35d0c539539e6dc29351838879771d2f3005c631e53cefbc7a85c0c9fc69

No PR created though

cc @dduportal in case you can see what's wrong in the update cli config from https://github.com/jenkinsci/bom/pull/1063

**Comment by timja** [comment]
https://github.com/jenkinsci/bom/pull/1131

**Comment by timja** [comment]
it's fixed now https://github.com/jenkinsci/bom/pull/1132

**Comment by jetersen** [comment]
Oh right I forgot to add a pull request section when bumping the version 😅
