### ISSUE TITLE
Remove `workflow-cps-global-lib`

### ISSUE THREAD

**Issue by jglick** [jenkinsci/bom#1172]
After #1168 we should not really need this deprecated plugin in the BOM. Probably need to first pick up releases of

- [x] https://github.com/jenkinsci/configuration-as-code-plugin/pull/1973
- [x] https://github.com/jenkinsci/git-plugin/pull/1274
- [x] https://github.com/jenkinsci/github-branch-source-plugin/pull/565

Should probably keep `git-server` since it will then still be used in at least [one place](https://github.com/jenkinsci/scriptler-plugin/blob/52a1e4bdc537f2757dd9d3f8c923e2225bc6ecf1/pom.xml#L52-L78).

**Comment by basil** [comment]
All dependent tasks are complete; should this ticket be prioritized now?

**Comment by MarkEWaite** [comment]
> All dependent tasks are complete; should this ticket be prioritized now?

Thanks for detecting it.  I submitted:

* #1740
