### ISSUE TITLE
Consider running PCT matrix for all lines on GitHub Action?

### ISSUE THREAD

**Issue by jetersen** [jenkinsci/bom#1350]
I been toying with the idea to generate github actions manifest to run PCT testing for each plugin. Potentially run the matrix for each line.
One the goal would be reduce the load on ci.jenkins.io and two Jenkins pipeline could default in the future to `mvn verify` if the PCT matrix would run faster and on all lines here on GitHub WDYT?
Another benefit would be would could take advantage of caching of maven dependencies and potential caching of WAR if we can find a good way to only update a single/few plugin.

So I had something like this in mind.

```mermaid
graph TD
    A[GitHub Actions] 
    A --> B(MVN Verify)
    B --> C[Prepare WAR 2.319.x]
    B --> D[Prepare WAR 2.332.x]
    B --> E[Prepare WAR 2.346.x]
    B --> F[Prepare WAR Weekly]
    C --> G[Plugin 1]
    C --> H[Plugin 2]
    C --> I[Plugin 3]
    D --> G1[Plugin 1]
    D --> H1[Plugin 2]
    D --> I1[Plugin 3]
    E --> G2[Plugin 1]
    E --> H2[Plugin 2]
    E --> I2[Plugin 3]
    F --> G3[Plugin 1]
    F --> H3[Plugin 2]
    F --> I3[Plugin 3]
```

cc @jglick @timja @basil

**Comment by jglick** [comment]
> reduce the load on ci.jenkins.io

Would rather learn what could be done to let ci.jenkins.io handle more load.

Or retain status quo—testing of intermediate lines (beyond what `sample-plugin/check.groovy` does) sometimes turns up technical problems (POM weirdness, PCT bugs) but is unlikely to inform us about genuine code incompatibilities.

> take advantage of caching of maven dependencies

https://github.com/jenkins-infra/helpdesk/issues/2752 would probably suffice, and is arguably safer and cleaner than `~/.m2/repository/` caching.

**Comment by jglick** [comment]
I do not think we plan to do anything like this, especially given #1593. CC @dduportal
