### ISSUE TITLE
`bootstrap5-api` is out of date

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#1803]
At the time of this writing, `bootstrap5-api` is managed at 5.2.0-1. The latest version is 5.2.1-3.

**Comment by MarkEWaite** [comment]
Thanks for noting that.

When we merged:

* #1513

we missed that it did not include the bootstrap5-api update that was proposed in

* #1475 

I've reopened #1475 in hopes that it will pass validation now and can be merged.

The gap highlights a broader concern that when I ignore a version update (matrix-auth plugin and jersey2-api plugin are examples), there needs to be some way to detect that the version update was ignored and not just allow that
