### ISSUE TITLE
`slack` is out of date

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#1805]
At the time of this writing, `slack` is managed at 629.vf00ea_cb_40d53. The latest version is 631.v40deea_40323b. Dependabot does not appear to have offered the update due to https://github.com/jenkinsci/incrementals-tools/issues/34.

**Comment by elmsdata** [comment]
Hi @basil and happy Tuesday! I work on a DevOps team where we are currently working on a Jenkins Plugin and while researching bom versions saw this issue. It's not blocking us but was wondering if you need any help with this version upgrade? It appears from other pull requests the project uses a dependabot to make incremental changes and I didn't see a contributing guide for the project. Please ignore if this is all part of automation but happy to help open a pull request to make this change for you! Hope you have a great week!

**Comment by basil** [comment]
A pull request to update `bom-weekly/pom.xml` with the latest version of the Slack plugin would resolve this issue. An alternative is to get the maintainer of the Slack plugin to release the latest `HEAD` (which contains https://github.com/jenkinsci/incrementals-tools/issues/34), at which point Dependabot should do the former automatically.

**Comment by elmsdata** [comment]
Thanks for clarifying @basil! I will try to open a pull request later next week and see if the Slack plugin maintainer update their dependency to the latest. Hope you have a great Thursday!

**Comment by basil** [comment]
The Slack plugin was just released 20 hours ago, so Dependabot should be offering a PR shortly.

**Comment by elmsdata** [comment]
Fantastic! I'll watch to see if the bot pulls the change, I find this process very fascinating and appreciate you explaining the process!

**Comment by timja** [comment]
Fixed in https://github.com/jenkinsci/bom/pull/1983
