### ISSUE TITLE
`workflow-job` is out of date

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#1807]
At the time of this writing, `workflow-job` is managed at 1254.v3f64639b_11dd. The latest version is 1268.v6eb_e2ee1a_85a. Dependabot does not appear to have offered the update due to jenkinsci/incrementals-tools#34.

**Comment by jglick** [comment]
Will check if releasing https://github.com/jenkinsci/workflow-job-plugin/pull/331 fixes this.
