### ISSUE TITLE
Add Docker Commons to the managed set

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#2096]
### What feature do you want to see added?

This is an API plugin and it is widely deployed, making it a perfect candidate for inclusion in the managed set.

**Comment by MarkEWaite** [comment]
The `docker-commons` plugin automated tests currently fail one test when run with Jenkins 2.410.  The tests pass with Jenkins 2.401.1 and earlier.

The failing test is:

```
mvn clean -DforkCount=1C -Djenkins.version=2.410 -Dtest=DockerServerCredentialsBindingTest#configRoundTrip verify
```

**Comment by MarkEWaite** [comment]
A new release of docker-commons API plugin will need to be released that includes at least:

* https://github.com/jenkinsci/docker-commons-plugin/pull/136

Without that change, automated tests of the docker commons plugin fail with Jenkins 2.410.

**Comment by jglick** [comment]
Merged, should get a release soon if all goes well.
