### ISSUE TITLE
BOM releases failing after long run time

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/bom#2120]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

3 attempts to generate a release of the plugin bill of materials have failed on ci.jenkins.io.  Issue reported as https://github.com/jenkins-infra/helpdesk/issues/3605 to request help from the infrastructure team.

The initial release of the 2.401.x line required 6 hours to complete.  The last 3 attempts to build for release failed with times ranging from 7 to 9 hours.

I think we should consider dropping 2.361.x as a BOM line because there are known security vulnerabilities disclosed in 2.361.x.  Once 2.401.1 releases on 31 May 2023, I'll submit a pull request proposing to drop 2.361.x

### Reproduction steps

1. Review the failing release builds

### Expected Results

Release build should pass

### Actual Results

Release build fails unexpectedly

**Comment by timja** [comment]
I wouldn't bother waiting it could just be dropped now imo

**Comment by MarkEWaite** [comment]
Fixed by #2171 that allows up to 6 retries and by the removal of 2.361.4 from the managed set.
