### ISSUE TITLE
Test on Java 21

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#2366]
As part of our goal of delivering Java 21 support, add PCT test coverage for Java 21. To preserve test coverage from Java 17, I am planning on testing weeklies on Java 21 and LTS lines on Java 17, but I do not feel strongly about this and could consider other test matrices.

**Comment by MarkEWaite** [comment]
> As part of our goal of delivering Java 21 support, add PCT test coverage for Java 21. To preserve test coverage from Java 17, I am planning on testing weeklies on Java 21 and LTS lines on Java 17, but I do not feel strongly about this and could consider other test matrices.

That seems like a very reasonable choice to me.  +1
