### ISSUE TITLE
Add Docker Hub/Registry Notification to the managed set

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#2439]
### What feature do you want to see added?

[This plugin](https://plugins.jenkins.io/dockerhub-notification/) has 1,886 installations. It is important to the Jenkins community and important to CloudBees, so it should be in this repository's test matrix.

**Comment by MarkEWaite** [comment]
Blocked on https://github.com/jenkinsci/dockerhub-notification-plugin/pull/44
