### ISSUE TITLE
Remove `data-tables`, `echarts`, and `prism` workaround

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#2683]
This ticket covers removing the workaround added in #2682 once the upstream issue is resolved. At the time of this writing, an upstream issue has not been filed, contra https://github.com/jenkinsci/bom/pull/2680#issuecomment-1823115582:

> if this workaround is adopted, an issue should **first** be filed against `analysis-pom`

(Emphasis mine.)

**Comment by MarkEWaite** [comment]
@uhafner can you guide me on your preferred location for an issue report for `analysis-pom`?  There isn't a component on https://issues.jenkins.io that seems to match the analysis-pom and GitHub issues are not enabled for the https://github.com/jenkinsci/analysis-pom-plugin repository.

**Comment by uhafner** [comment]
You can file the issue in one of the affected downstream libraries, e.g. in prism.

**Comment by basil** [comment]
Fixed in https://github.com/jenkinsci/bom/pull/2719.
