### ISSUE TITLE
Revert declarative-pipeline-migration-assistant plugin deletion from BOM

### ISSUE THREAD

**Issue by alecharp** [jenkinsci/bom#2823]
### Jenkins and plugins versions report

`bom-weekly` as modified in https://github.com/jenkinsci/bom/pull/2819

### What Operating System are you using (both controller, and any agents involved in the problem)?

Irrelevant

### Reproduction steps

Not relevant.

### Expected Results

`declarative-pipeline-migration-assistant` and `declarative-pipeline-migration-assistant-api` are part of the BOM definition of the `bom-weekly` module.
`declarative-pipeline-migration-assistant` also needs to be added to the `sample-plugin` as a test dependency

### Actual Results

The plugins are not present in the BOM.

### Anything else?

This is basically a revert of https://github.com/jenkinsci/bom/pull/2819/commits/60ac7d8b522fadbda86b28a334c4dd9f703156a0 once https://github.com/jenkinsci/declarative-pipeline-migration-assistant-plugin/pull/237 is released.

**Comment by alecharp** [comment]
The plugin was release as `1.6.2`.
We can start reverting the removal of the plugin from the weekly BOM.

**Comment by alecharp** [comment]
See https://github.com/jenkinsci/bom/pull/2819/commits/49d3a55178ef3a87e0fe16dc2fe2a762d9459da0

**Comment by MarkEWaite** [comment]
Done in:

* #2819
