### ISSUE TITLE
Cannot validate commit 1331fa2

### ISSUE THREAD

**Issue by alecharp** [jenkinsci/bom#2916]
As I'm trying to release the BOM, I cannot validate the commit https://github.com/jenkinsci/bom/commit/1331fa2ef7e5fc84a1e42743a7c1ac057a9f5ee2.

The test error we can see at https://ci.jenkins.io/job/Tools/job/bom/job/master/2494/testReport/io.jenkins.blueocean.service.embedded/PipelineApiTest/pct_blueocean_plugin_2_426_x___testPipelineQueue/ is reproducible on all new commits since last release but even on last release commit.

I cannot debug the test outside of the BOM as I cannot get my setup to build blueocean. (cc @olamy).

I won't be able to investigate more until monday and I don't know for how long this would delay the release of the BOM.

Should we unlock the `master` branch in the meantime or keep trying to figure out what is happening on that precise commit @MarkEWaite ?

**Comment by MarkEWaite** [comment]
> Should we unlock the master branch in the meantime or keep trying to figure out what is happening on that precise commit @MarkEWaite ?

I think we should unlock the master branch, merge the pending items in the queue, then run a `weekly-test`.  The `weekly-test` is not as expensive as a release build and may help us better understand.

I'm happy to launch the weekly-test once the changes are merged @alecharp . Thanks so much for your investigation.  Delaying the release until next week is not harmful to anyone as far as I know.

**Comment by MarkEWaite** [comment]
I've unlocked the master branch and will merge the pending pull requests and start a weekly test

**Comment by MarkEWaite** [comment]
Pending pull requests have been merged and I've started a weekly test using:

* #2912

**Comment by alecharp** [comment]
Proof that it was a flaky test: the release was validated and finalized just now.

**Comment by jglick** [comment]
> The test error we can see at…

By the way when reporting errors please either paste in the stack trace, or link to a GH Checks run that recorded it, as Jenkins builds are frequently deleted to save space.
