### ISSUE TITLE
Recent ssh-credentials release fails tests in subversion and apache-mina-sshd-core

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/bom#3050]
### Jenkins and plugins versions report

https://github.com/jenkinsci/bom/pull/3049#issue-2203579659 describes the details of the test failures with the most recent ssh-credenitals plugin release.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

1. Include the most recent release of ssh-credentials (326.v7fcb_a_ef6194b_) in a plugin bill of materials
2. Run the Apache Mina sshd core tests with `LINE=weekly PLUGINS=mina-sshd-api-core  bash local-test.sh` and confirm there is a test failure
3. Run the subversion tests with `$ PLUGINS=subversion TEST=CompareAgainstBaselineCallableTest bash local-test.sh` and confirm there is a failure

### Expected Results

All tests pass

### Actual Results

Some tests fail

### Anything else?

The most recent ssh-credentials plugin makes the trilead-api plugin optional.

### Are you interested in contributing a fix?

I would prefer that someone else contributes the fix.

**Comment by basil** [comment]
#3061
