### ISSUE TITLE
Remove Lockable Resources workaround

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#3066]
#3031 temporarily excluded two tests pending the fix for https://github.com/jenkinsci/lockable-resources-plugin/issues/634. When a new version of Lockable Resource is released with fixes for Data Tables 2.x, these temporary test exclusions should be removed.

**Comment by mPokornyETM** [comment]
will be fine, when somebody check the changes here
https://github.com/jenkinsci/lockable-resources-plugin/issues/634

thx

**Comment by basil** [comment]
Thanks @mPokornyETM! Any chance we could get a backport to 2.426.x? The test is now passing on the latest line, but still failing on the 2.426.x and earlier lines, because on those lines Data Tables is upgraded, but Lockable Resources is still pinned to the old version without the fix you just released.

Instructions here: https://gist.github.com/jglick/86a30894446ed38f918050c1180483e2

If the answer is "No", that is completely understandable and no problem at all. We will then have to leave this ticket open, with the workaround in place, for the next 6 months or so until this repository drops support for the 2.426.x line, at which point the workaround can be removed and this ticket can then be closed.

**Comment by mPokornyETM** [comment]
Interesting. I have no idea why it fails. I will check it, but I thnik, I does not have time for next few mounts. Therefore it make also no sense.
sry

**Comment by basil** [comment]
Thinking about this some more, I suppose another alternative would be to downgrade Data Tables on the 2.426.x line to 1.x, which would be equivalent to the user scenario of rejecting the upgrade due to its incompatibility with Lockable Resources. That could be a good compromise.

**Comment by basil** [comment]
I have backported the changes to the 2.426.x line in https://github.com/jenkinsci/lockable-resources-plugin/pull/653
