### ISSUE TITLE
Declarative Pipeline plugins 2.2184.v0b_358b_953e69 cause `ssh-agent` plugin tests to fail

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/bom#3106]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Not relevant to this report
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 22.04

### Reproduction steps

1. Checkout the plugin bill of materials master branch and run `LINE=weekly PLUGINS=ssh-agent  bash local-test.sh`.  Confirm that the tests fail while declarative Pipeline plugins `2.2188.v26e255fd2984` are used and that they succeed when declarative Pipeline plugins `2.2184.v0b_358b_953e69` are used

### Expected Results

The tests of `ssh-agent` should pass

### Actual Results

Tests of `ssh-agent` fail as noted in the [ci.jenkins.io test report](https://ci.jenkins.io/job/Tools/job/bom/job/PR-3104/1/testReport/)

### Anything else?

The interesting commit in the recent declarative Pipeline plugin release is:

* https://github.com/jenkinsci/pipeline-model-definition-plugin/issues/706

@jglick is that something that you could investigate?

**Comment by jglick** [comment]
Stumped so far.

Locally in the plugin:

```bash
mvn -Dtest=SSHAgentStepWorkflowTest#sshAgentAvailable -DoverrideWar=…/bom/target/megawar-weekly.war -Djenkins.version=2.452 -DuseUpperBounds=true test
```

Normally:

```
debug1: Next authentication method: publickey
debug1: Offering public key: …/workspace/sshAgentAvailable@tmp/private_key_3050994223447549571.key RSA SHA256:… agent
debug1: Server accepts key: …/workspace/sshAgentAvailable@tmp/private_key_3050994223447549571.key RSA SHA256:… agent
```

When test fails, that last line is not printed. There is no further interesting diagnostic, just

```
debug1: No more authentication methods to try.
cloudbees@localhost: Permission denied (keyboard-interactive,publickey).
```

Merely bumping the `pipeline-model-definition` suite via `<dependencyManagement>` (and thus removing `git-client` from the test classpath) does not cause the test to fail; some other change from `overrideWar` is required.

**Comment by jglick** [comment]
#3111
