### ISSUE TITLE
`net.bytebuddy:byte-buddy` upper bound issue with `3010.vec758b_8e7da_3`

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/bom#3155]
### Jenkins and plugins versions report

All

### What Operating System are you using (both controller, and any agents involved in the problem)?

All

### Reproduction steps

Hi,

This is not exactly an issue with the bom but I've seen upper bound issue on some recent bom update

https://ci.jenkins.io/job/Plugins/job/postgresql-fingerprint-storage-plugin/job/PR-313/1/console

```
05:28:37  Require upper bound dependencies error for net.bytebuddy:byte-buddy:1.12.18 paths to dependency are:
05:28:37  +-io.jenkins.plugins:postgresql-fingerprint-storage:267.v11ef13b_908c8
05:28:37    +-org.jenkins-ci.plugins:database:230.v701f20b_8b_f95
05:28:37      +-org.hibernate:hibernate-entitymanager:5.6.15.Final
05:28:37        +-net.bytebuddy:byte-buddy:1.12.18
05:28:37  and
05:28:37  +-io.jenkins.plugins:postgresql-fingerprint-storage:267.v11ef13b_908c8
05:28:37    +-org.jenkins-ci.plugins:jackson2-api:2.17.0-379.v02de8ec9f64c
05:28:37      +-com.fasterxml.jackson.core:jackson-databind:2.17.0
05:28:37        +-net.bytebuddy:byte-buddy:1.14.9
05:28:37  and
05:28:37  +-io.jenkins.plugins:postgresql-fingerprint-storage:267.v11ef13b_908c8
05:28:37    +-org.jenkins-ci.plugins:database:230.v701f20b_8b_f95
05:28:37      +-org.hibernate:hibernate-entitymanager:5.6.15.Final
05:28:37        +-org.hibernate:hibernate-core:5.6.15.Final
05:28:37          +-net.bytebuddy:byte-buddy:1.12.18
```

I happen when database plugin and jackson2-api are in the classpath 

My feeling is that perhaps byte-buddy deserve and API plugin ?

Regards,

### Expected Results

No issue when bumping bom version

### Actual Results

```
05:28:37  Require upper bound dependencies error for net.bytebuddy:byte-buddy:1.12.18 paths to dependency are:
05:28:37  +-io.jenkins.plugins:postgresql-fingerprint-storage:267.v11ef13b_908c8
05:28:37    +-org.jenkins-ci.plugins:database:230.v701f20b_8b_f95
05:28:37      +-org.hibernate:hibernate-entitymanager:5.6.15.Final
05:28:37        +-net.bytebuddy:byte-buddy:1.12.18
05:28:37  and
05:28:37  +-io.jenkins.plugins:postgresql-fingerprint-storage:267.v11ef13b_908c8
05:28:37    +-org.jenkins-ci.plugins:jackson2-api:2.17.0-379.v02de8ec9f64c
05:28:37      +-com.fasterxml.jackson.core:jackson-databind:2.17.0
05:28:37        +-net.bytebuddy:byte-buddy:1.14.9
05:28:37  and
05:28:37  +-io.jenkins.plugins:postgresql-fingerprint-storage:267.v11ef13b_908c8
05:28:37    +-org.jenkins-ci.plugins:database:230.v701f20b_8b_f95
05:28:37      +-org.hibernate:hibernate-entitymanager:5.6.15.Final
05:28:37        +-org.hibernate:hibernate-core:5.6.15.Final
05:28:37          +-net.bytebuddy:byte-buddy:1.12.18
```

### Anything else?

No

### Are you interested in contributing a fix?

I can create the API plugin and perform the needed PR

**Comment by basil** [comment]
Yes, a library plugin is our traditional solution to this problem. The one thing I am surprised about is that we don't see the same Enforcer error in the `sample-plugin/` directory in BOM, which is designed to catch cases like this. Come to think of it, the last time I had to add an exclusion to `sample-plugin/pom.xml` was in March of 2023. I can't immediately see why that Enforcer error occurs in `postgresql-fingerprint-storage-plugin` but not in `sample-plugin`. Might be worth thinking about that further, or looking into #683.
