### ISSUE TITLE
Add Promoted Builds to managed set

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/bom#3171]
### What feature do you want to see added?

Add the [promoted builds plugin](https://plugins.jenkins.io/promoted-builds/) to the managed set of plugins because it has over 10000 installations and is an optional dependency of several popular plugins that are already included in the plugin BOM:

* [Git plugin](https://plugins.jenkins.io/git/dependencies/)
* [Parameterized trigger plugin](https://plugins.jenkins.io/parameterized-trigger/dependencies/)

Those two optional dependencies were updated in releases of the respective plugins that were verified with Jenkins 2.457.

* https://github.com/jenkinsci/bom/pull/3185

It is also a test dependency of a plugin in the plugin BOM:

* [Maven integration plugin](https://plugins.jenkins.io/maven-plugin/dependencies/)

It is also an optional dependency of another "top 250 plugin":

* [Plugin usage plugin](https://plugins.jenkins.io/plugin-usage-plugin/dependencies/) (not in plugin BOM)

It is also a test dependency of "top 250 plugins": 

* [Infrastructure for publish over X plugin](https://plugins.jenkins.io/publish-over/dependencies/) (not in plugin BOM)
* [Disk usage plugin](https://plugins.jenkins.io/disk-usage/dependencies/) (not in plugin BOM)

### Upstream changes

Will probably also require inclusion of the Job DSL plugin in the managed set.  I failed in my attempt to add Job DSL plugin in:

* #3170

### Are you interested in contributing this feature?

Failed in my attempt to add the promoted builds plugin to the managed set in:

* #3170

**Comment by basil** [comment]
> Will probably also require inclusion of the Job DSL plugin in the managed set. I failed in my attempt to add Job DSL plugin

@MarkEWaite Job DSL is now included, so this ticket should be unblocked.

**Comment by MarkEWaite** [comment]
> > Will probably also require inclusion of the Job DSL plugin in the managed set. I failed in my attempt to add Job DSL plugin
> 
> @MarkEWaite Job DSL is now included, so this ticket should be unblocked.

Thanks.  I've started an attempt to add promoted builds to the bom as well using the job-dsl PR as a starting point.
