### ISSUE TITLE
bom-release-issue-add-release-comment.sh outputs `unknown flag: --json`

### ISSUE THREAD

**Issue by gounthar** [jenkinsci/bom#4006]
### Jenkins and plugins versions report

./bom-release-issue-add-release-comment.sh
unknown flag: --json

Usage:  gh release list [flags]

Flags:
      --exclude-drafts         Exclude draft releases
      --exclude-pre-releases   Exclude pre-releases
  -L, --limit int              Maximum number of items to fetch (default 30)

https://github.com/jenkinsci/bom/issues/3997#issuecomment-2493702988
https://github.com/jenkinsci/bom/issues/3997

### What Operating System are you using (both controller, and any agents involved in the problem)?

WSL2/Debian

```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Reproduction steps

Follow the [contributing guide](https://github.com/jenkinsci/bom/blob/master/CONTRIBUTING.md).

### Expected Results

No error message.

### Actual Results

./bom-release-issue-add-release-comment.sh
unknown flag: --json

Usage:  gh release list [flags]

Flags:
      --exclude-drafts         Exclude draft releases
      --exclude-pre-releases   Exclude pre-releases
  -L, --limit int              Maximum number of items to fetch (default 30)

https://github.com/jenkinsci/bom/issues/3997#issuecomment-2493702988
https://github.com/jenkinsci/bom/issues/3997

**Comment by MarkEWaite** [comment]
I think that your `gh` release is outdated on that machine.  Current release is 2.62.0.

**Comment by gounthar** [comment]
Indeed:

```
gh version
gh version 2.23.0 (2023-02-27 Debian 2.23.0+dfsg1-1)
https://github.com/cli/cli/releases/tag/v2.23.0
```

Thanks for the tip, Mark. 👍 
My machine is up to date thanks to `apt`, but I guess I installed `gh` in another way. 🤔 

I'll update it, and see how things go for the next release.

**Comment by MarkEWaite** [comment]
It was available for me.

**Comment by gounthar** [comment]
It worked for me last week with the latest `gh` command.
