### ISSUE TITLE
Use JEP-229

### ISSUE THREAD

**Issue by jglick** [jenkinsci/bom#496]
It is annoying to have to do reincrementalify `sample-plugin` after every release, and easily forgotten (https://github.com/jenkinsci/bom/commit/2b7c48813825243dc45b21f83319cfff0a591bcd was delayed by a week). See also https://issues.jenkins.io/browse/JENKINS-58641. Better to use JEP-229 to release on `workflow_dispatch` (I do not think we want automatic releases from this component).

**Comment by jetersen** [comment]
Any reason why sample plugin is not reincrementalify otherwise I would suggest using the hook that exist in plugin pom directly.

**Comment by timja** [comment]
sounds good to me

**Comment by jetersen** [comment]
@timja which part? using JEP-229 or my suggestion to fix sample plugin? or both? 🙈

**Comment by jetersen** [comment]
You could also activate the release from release published instead of `workflow_dispatch` ?

**Comment by timja** [comment]
JEP-229, if you know how to fix the re incrementalify but then sure,

we already have that enabled though from what I can tell: https://github.com/jenkinsci/bom/blob/master/.mvn/maven.config#L2

**Comment by jglick** [comment]
> Any reason why sample plugin is not reincrementalify

Yes, because it has a different `parent`.

**Comment by jetersen** [comment]
@jglick seems the repo still uses release-drafter probot app. You properly want to remove it.
