### ISSUE TITLE
Latest Bom release with huge version bump for 807.v6d348e44c987

### ISSUE THREAD

**Issue by viceice** [jenkinsci/bom#510]
Is it expected to have `807.v6d348e44c987` as a release? It's a huge bump from `bom-29` to `807.v6d348e44c987` git tag.

I've got a update pr from v29 to v807.v6d348e44c987 [here](https://github.com/visualon/jenkins-gitea-plugin/pull/17).

https://github.com/jenkinsci/bom/releases/tag/807.v6d348e44c987

**Comment by jetersen** [comment]
This is expected, see #508

**Comment by viceice** [comment]
ok, thanks.
