### ISSUE TITLE
1181.v04b_21d4b_0d6c release is missing on Github

### ISSUE THREAD

**Issue by offa** [jenkinsci/bom#918]
### Describe your use-case which is not covered by existing documentation.

There's no 1181.v04b_21d4b_0d6c release listed on Github (Maven package, Git tag etc. are fine though).

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

https://github.com/jenkinsci/bom/releases

**Comment by timja** [comment]
Fixed https://github.com/jenkinsci/bom/releases/tag/1181.v04b_21d4b_0d6c

Was due to a GitHub bug that prevent release drafter from working, they reverted the change

**Comment by offa** [comment]
Thanks!
