### ISSUE TITLE
Suppress Dependabot prompts for `999999-SNAPSHOT`

### ISSUE THREAD

**Issue by jglick** [jenkinsci/bom#982]
#913, #980. I guess there are two contributing issues:

* Dependabot’s Maven plugin does not get that `*-SNAPSHOT` is not a release. This fact is built into Maven core IIRC. Seems like a DB bug.
* The `snapshots` repo is even being consulted. I think we could configure DB specifically to use the `releases` repo rather than `public` as in the POM. Would be a pain to do that for _all_ DB-enabled repos but if `bom` is especially affected it would be reasonable.

**Comment by jglick** [comment]
> Dependabot does _not_ prompt for `999999-SNAPSHOT`

Interesting—do you know of cases where such versions have been deployed but not offered by DB?

`2.13.1-999999-SNAPSHOT` etc. are snapshot versions according to Maven semantics, again to my recollection: anything ending in `-SNAPSHOT` (as well as a more technical pattern used for timestamped snapshots). Such version numbers can arise in the alternate JEP-229 idiom used for library wrapper plugins

```xml
<version>${revision}-${changelist}</version>
```

if you `mvn deploy`. I cannot think of any particular reason why DB should treat such unremarkable-looking version strings as releases, but who knows.

> In either case it is not appropriate to open an issue against `bom`

Filed just because it is an occasional annoyance that we may be able to work around in this repo, and/or as a tracking issue reminding us to research and file an upstream bug.

**Comment by basil** [comment]
> do you know of cases where such versions have been deployed but not offered by DB?

https://repo.jenkins-ci.org/artifactory/public/org/jenkins-ci/plugins/script-security/999999-SNAPSHOT/

> as a tracking issue reminding us to research and file an upstream bug

It is not appropriate to file JEP-229 specific tracking issues in the `bom` component. Such tracking issues should be filed against the JEP-229 docs or one of the JEP-229 tooling repositories.

**Comment by jglick** [comment]
Granted. This repository just seemed most likely to be affected, and so the likely locus of any workaround. Anyway, I will try to move it.
